
# This yml will be run outside a playbook.

- name: Make sure we have a 'wheel' group
  group:
    name: wheel
    state: present
  tags:
    - add-deployer

- name: Allow 'wheel' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
  tags:
    - add-deployer

- name: Add sudoers users to wheel group
  user: name=deployer groups=wheel append=yes state=present createhome=yes
  tags:
    - add-deployer

- name: Set up authorized keys for the deployer user
  authorized_key: user=deployer key="{{ lookup('file', ansible_ssh_public_key_file) }}"
  tags:
    - add-deployer
