- hosts: network
  become: yes
  vars_files:
    - vars/network
  roles:
    - network
  max_fail_percentage: 0

- hosts: repository
  become: yes
  vars_files:
    - vars/repository
  roles:
    - repository
  max_fail_percentage: 0

