
- name: Install jenkins
  shell: "{{item}}"
  with_items:
    - "wget https://pkg.jenkins.io/redhat-stable/jenkins-2.107.3-1.1.noarch.rpm"
    - "yum localinstall -y jenkins-2.107.3-1.1.noarch.rpm"
  tags:
    - slow