- name: Install gd-tools
  copy:
    src: gd-tools.py
    dest: /usr/bin/gd-tools
    owner: root
    group: root
    mode: 0777

- name: Install local repository
  copy:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    owner: root
    group: root
    mode: 0777
  with_items:
    - {'src': 'CentOS-Base.repo', 'dest': '/etc/yum.repos.d/CentOS-Base.repo'}
    - {'src': 'CentOS-extra.repo', 'dest': '/etc/yum.repos.d/CentOS-extra.repo'}
    - {'src': 'epel.repo', 'dest': '/etc/yum.repos.d/epel.repo'}
   # - {'src': 'degols.repo', 'dest': '/etc/yum.repos.d/degols.repo'}

- name: Update repository list
  shell: 'yum clean all && yum check-update || test $? -eq 100'

- name: Install various tools tools
  yum:
    name: "{{item}}"
    state: latest
  with_items:
    - yum-utils

- name: Create directory for configuration
  file:
    path: "{{item}}"
    state: directory
    owner: root
    group: root
    mode: 0644
  with_items:
    - /etc/gd/default
    - /etc/gd/local

- name: Remove rsyslog
  # We use journalctl directly so it's redundant
  yum:
    name: rsyslog
    state: absent
