- name: Add Docker repository (stable)
  shell:  yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

- name: Install docker-ce
  yum:
    name: "{{item.package}}"
    state: present
  with_items:
    - { package: "docker-ce" } # Last tested version: 18.05.0.ce-3
    - { package: "docker-compose" } # Last tested version: 1.9.0-5
